# Generated by Django 2.1 on 2018-09-25 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_percent', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('phone_number', models.IntegerField(default=0)),
                ('pwd', models.CharField(default=None, max_length=50)),
                ('school_name', models.CharField(default=None, max_length=50)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(choices=[('login', '29-5'), ('share_once', '99-19'), ('share_twice', '149-39')], max_length=20)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('image_url', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('CLOSE', '已取消'), ('GENERATE', '已生成'), ('PAY', '已付款')], default='CLOSE', max_length=50)),
                ('price', models.FloatField(default=9.9)),
                ('generate_info', models.CharField(max_length=1000)),
                ('account_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Account_info')),
            ],
        ),
        migrations.CreateModel(
            name='Weixin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='weixin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Weixin_user'),
        ),
        migrations.AddField(
            model_name='class_info',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weixin.Order_info'),
        ),
        migrations.AddField(
            model_name='car_info',
            name='goods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weixin.Goods'),
        ),
        migrations.AddField(
            model_name='car_info',
            name='weixin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Weixin_user'),
        ),
        migrations.AddField(
            model_name='account_info',
            name='weixin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Weixin_user'),
        ),
    ]
