# Generated by Django 2.1 on 2018-09-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='account_info',
        ),
        migrations.AddField(
            model_name='order_info',
            name='weixin_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weixin.Weixin_user'),
        ),
    ]
