# Generated by Django 2.1 on 2018-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20180925_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_info',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
